global:
  scrape_interval: 15s      # How often to scrape
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape YOUR Rust monitor app!
  - job_name: 'rust-cloud-monitor'
    static_configs:
      - targets: ['monitor:8080']  # 'monitor' is the service name in docker-compose
    metrics_path: '/metrics'       # Your /metrics endpoint
    scrape_interval: 10s           # Scrape every 10 seconds